# Generated by Django 4.1.7 on 2023-03-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('price_without_profit', models.IntegerField()),
                ('price_with_profit', models.IntegerField()),
                ('profit_percCent', models.IntegerField()),
            ],
        ),
    ]
